name: storybook_flutter_generator_annotation
description: A code generator for storybook_flutter.
version: 0.1.0
publish_to: none
resolution: workspace
repository: https://github.com/Atsumi3/storybook_flutter_generator
issue_tracker: https://github.com/Atsumi3/storybook_flutter_generator/issues

environment:
  sdk: ">=3.9.0 <4.0.0"
